version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  AfterInstall:
    - location: scripts/start_server.sh
	  runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
	  runas: root
